site_name: Project-Bayron
nav:
    - Home: index.md
    - Consolas: consolas.md
    - Sony: sony.md
    - Nintendo: nintendo.md
    - Microsoft: microsoft.md
theme: readthedocs
markdown_extensions:
    - attr_list